### ISSUE TITLE
macOS Python 3.10 builds are broken

### ISSUE THREAD

**Issue by chrisburr** [conda-forge/pyyaml-feedstock#40]
I've haven't debugged properly but the Python 3.10 builds of PyYAML for macOS are missing the actual Python package in `site-packages`:

```
$ ls pyyaml-*py39*/lib/python*/site-packages
pyyaml-5.4.1-py39h89e85a6_1/lib/python3.9/site-packages:
    PyYAML-5.4.1-py3.9-macosx-10.9-x86_64.egg-info
    _yaml
    yaml

pyyaml-6.0-py39h3811e60_1/lib/python3.9/site-packages:
    PyYAML-6.0-py3.9-linux-x86_64.egg-info
    _yaml
    yaml

pyyaml-6.0-py39h5161555_2/lib/python3.9/site-packages:
    PyYAML-6.0-py3.9-macosx-11.0-arm64.egg-info
    _yaml
    yaml

$ ls pyyaml-*py310*/lib/python*/site-packages
pyyaml-6.0-py310he2143c4_1/lib/python3.10/site-packages:
    PyYAML-6.0-py3.10-macosx-11.0-arm64.egg
    PyYAML.pth

pyyaml-6.0-py310he2143c4_2/lib/python3.10/site-packages:
    PyYAML-6.0-py3.10-macosx-11.0-arm64.egg
    PyYAML.pth

pyyaml-6.0-py310he24745e_2/lib/python3.10/site-packages:
    PyYAML-6.0-py3.10-macosx-10.9-x86_64.egg
    PyYAML.pth
```

See also: https://github.com/conda-forge/awkward-feedstock/pull/77

cc @conda-forge/pyyaml

**Comment by jakirkham** [comment]
It’s unclear from the info above which packages, build numbers, architectures, OSes, etc. are being used. Can you please include this info Chris?

**Comment by jakirkham** [comment]
There was this change ( https://github.com/conda-forge/pyyaml-feedstock/pull/39 ) that went in recently that was intended to fix macOS ARM packages. Related to the question above it is unclear if we are picking up the new packages or the old ones, which would be important in narrowing down the issue

cc @erykoff (for awareness)

**Comment by erykoff** [comment]
Oh my.  The patch that I put in *should* have only applied to `py<39`.

**Comment by erykoff** [comment]
Specifically this line: https://github.com/conda-forge/pyyaml-feedstock/blob/master/recipe/meta.yaml#L12 .

**Comment by erykoff** [comment]
Oh! I see above that both build 1 (before I was mucking about) and build 2 (after my fix) were both broken?  
On the other hand, just now I on osx-arm64 I was able to import `yaml` and `yaml.cyaml` on osx-arm64 with both python 3.8 and 3.10, new build number -2.

**Comment by henryiii** [comment]
Does this have to build with [raw setup.py usage](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html)?

**Comment by henryiii** [comment]
Manually forcing variables like that inside setup.py is rather unfriendly. Wouldn’t it be fine to apply the patch for all Python versions? Possibly even get rid of that line upstream?

**Comment by jakirkham** [comment]
Yeah it's kind of hard to move this one to `pip`. Was trying this last night ( https://github.com/conda-forge/pyyaml-feedstock/pull/42 )

Agreed. Also mentioned this during review ( https://github.com/conda-forge/pyyaml-feedstock/pull/39#issuecomment-960159258 ). Raised issue ( https://github.com/yaml/pyyaml/issues/584 )

**Comment by erykoff** [comment]
Aside from the question on whether this was wise from pyyaml, I'm actually not sure what the problem is or if there is a problem.  For python3.10 the `_yaml` code is contained within `PyYAML-6.0-py3.10-macosx-11.0-arm64.egg`, while with python3.9 and earlier we have the separation of `PyYAML-5.4.1-py3.9-macosx-10.9-x86_64.egg-info` and the `_yaml` code.  Is this simply just some packaging changes that were defaulted in python?

**Comment by jakirkham** [comment]
Ok so got `pip` to work in PR ( https://github.com/conda-forge/pyyaml-feedstock/pull/42 ). That seems to avoid producing `.egg` files, which I'm guessing is the core of the issue here. Going to try and get that in.

Though there may be other issues we are still missing here. So going to leave this open for now.

**Comment by jakirkham** [comment]
Ok that PR has been merged and packages uploaded. Probably will take a bit for them to mirror over to CDN.

**Comment by jakirkham** [comment]
So it looks like `awkward`'s CI passed. So presumably the main point of this issue is resolved.

Ok to leave open until the remaining items in this thread are addressed or close and simply track in other issues. Please share your thoughts :)

**Comment by chrisburr** [comment]
Both `yaml` and `_yaml` are now in the expected place so I think this can be closed.

Thank you very much for taking care of this @jakirkham!

**Comment by jakirkham** [comment]
Thanks Chris! 😄

If you have time, would appreciate your help in issue ( https://github.com/yaml/pyyaml/issues/584 )
