### ISSUE TITLE
Could an older version of this feedstock be built for pypy3.8,pypy3.9

### ISSUE THREAD

**Issue by mattip** [conda-forge/pyyaml-feedstock#44]
### Comment:

In PR #43 the 6.0 version of the feedstock was built for pypy3.8/3.9. It turns out the awscli package pins `pyyaml >=3.10,<5.5`, which then fails to build since only pyyaml 6.0 is available. Would it be acceptable to build an older version for pypy3.8/3.9 that satifies that requirement. See [this comment](https://github.com/conda-forge/awscli-feedstock/pull/1113#issuecomment-1196315258) for a request to loosen the pin instead, I am not sure what is easier.

**Comment by tkelman** [comment]
I see there's a branch https://github.com/conda-forge/pyyaml-feedstock/tree/v5.4.x here that looks like it could be used for this purpose? Maybe needs cherry picking in a lot of the pypy-related build updates that have happened on main?
